-- MySQL Script generated by MySQL Workbench
-- Thu Jun 26 20:57:51 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`GeoPoint`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`GeoPoint` ;

CREATE TABLE IF NOT EXISTS `mydb`.`GeoPoint` (
  `id` CHAR(36) NULL DEFAULT NULL,
  `latitude` DOUBLE NOT NULL,
  `longitude` DOUBLE NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`Skill`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Skill` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Skill` (
  `id` CHAR(36) NULL DEFAULT NULL,
  `name` VARCHAR(100) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`Calendar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Calendar` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Calendar` (
  `id` CHAR(36) NULL DEFAULT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`TimeRange`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TimeRange` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TimeRange` (
  `id` CHAR(36) NULL DEFAULT NULL,
  `calendar_id` CHAR(36) NULL DEFAULT NULL,
  `start_time` DATETIME NOT NULL,
  `end_time` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX (`calendar_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`calendar_id`)
    REFERENCES `mydb`.`Calendar` (`id`)
    ON DELETE CASCADE);


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`User` ;

CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `id` CHAR(36) NULL DEFAULT NULL,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `preferred_radius` DOUBLE NULL DEFAULT NULL,
  `location_id` CHAR(36) NULL DEFAULT NULL,
  `calendar_id` CHAR(36) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX (`email` ASC) VISIBLE,
  INDEX (`location_id` ASC) VISIBLE,
  INDEX (`calendar_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`location_id`)
    REFERENCES `mydb`.`GeoPoint` (`id`),
  CONSTRAINT ``
    FOREIGN KEY (`calendar_id`)
    REFERENCES `mydb`.`Calendar` (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`Teacher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Teacher` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Teacher` (
  `id` CHAR(36) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT ``
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`User` (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`Session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Session` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Session` (
  `id` CHAR(36) NULL DEFAULT NULL,
  `title` VARCHAR(200) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `location_id` CHAR(36) NULL DEFAULT NULL,
  `teacher_id` CHAR(36) NULL DEFAULT NULL,
  `skill_id` CHAR(36) NULL DEFAULT NULL,
  `time_start` DATETIME NOT NULL,
  `time_end` DATETIME NOT NULL,
  `time_range_id` CHAR(36) NULL DEFAULT NULL,
  `createdAt` VARCHAR(45) NULL,
  `User_id` CHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX (`location_id` ASC) VISIBLE,
  INDEX (`teacher_id` ASC) VISIBLE,
  INDEX (`skill_id` ASC) VISIBLE,
  INDEX (`time_range_id` ASC) VISIBLE,
  INDEX `fk_Session_User1_idx` (`User_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`location_id`)
    REFERENCES `mydb`.`GeoPoint` (`id`),
  CONSTRAINT ``
    FOREIGN KEY (`teacher_id`)
    REFERENCES `mydb`.`Teacher` (`id`),
  CONSTRAINT ``
    FOREIGN KEY (`skill_id`)
    REFERENCES `mydb`.`Skill` (`id`),
  CONSTRAINT ``
    FOREIGN KEY (`time_range_id`)
    REFERENCES `mydb`.`TimeRange` (`id`),
  CONSTRAINT `fk_Session_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `mydb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
